export type Gender = 'Male' | 'Female';
export type AppointmentStatus = 'Consultant' | 'Contract of Service' | 'Contractual' | 'Co-Terminous' | 'Casual' | 'Elective' | 'Job Order' | 'Permanent' | 'Probationary' | 'Temporary';
export type EmployeeStatus = 'Active' | 'Inactive';

export interface Employee {
  id: string;
  lastName: string;
  firstName: string;
  middleName: string;
  dateOfBirth?: string;
  gender: Gender;
  officeHospitalName: string;
  appointmentStatus: AppointmentStatus;
  appointmentFrom?: string;
  appointmentTo?: string;
  aoNumber?: string;
  aoYear?: string;
  aoType?: 'Detailed' | 'Designated' | 'Recalled';
  status: EmployeeStatus;
  positionFunction: string;
  dateOfEmployment: string;
  dateOfSeparation?: string;
  reasonForSeparation?: string;
  motherUnit?: string;
  detailedTo?: string;
  detailedDivision?: string;
  detailedOrderFrom?: string;
  detailedOrderTo?: string;
  designatedPositionFunction?: string;
  designatedOrderFrom?: string;
  designatedOrderTo?: string;
  recalledFrom?: string;
  recalledTo?: string;
  recalledOrderFrom?: string;
  recalledOrderTo?: string;
  fileboxLocation?: string;
  file201Status?: string;
  profilePicture?: string;
  yellowBoxId?: string;
  yellowBox?: {
    id: string;
    boxLabel: string;
    office: string;
    type: string;
  };
  createdAt: string;
  updatedAt: string;
}

export interface EmployeeFormData {
  id: string;
  lastName: string;
  firstName: string;
  middleName: string;
  dateOfBirth: string;
  gender: Gender | '';
  officeHospitalName: string;
  appointmentStatus: AppointmentStatus | '';
  appointmentFrom: string;
  appointmentTo: string;
  aoNumber: string;
  aoYear: string;
  aoType: 'Detailed' | 'Designated' | 'Recalled' | '';
  status: EmployeeStatus;
  positionFunction: string;
  dateOfEmployment: string;
  dateOfSeparation: string;
  reasonForSeparation: string;
  motherUnit: string;
  detailedTo: string;
  detailedDivision: string;
  detailedOrderFrom: string;
  detailedOrderTo: string;
  designatedPositionFunction: string;
  designatedOrderFrom: string;
  designatedOrderTo: string;
  recalledFrom: string;
  recalledTo: string;
  recalledOrderFrom: string;
  recalledOrderTo: string;
  fileboxLocation: string;
  file201Status: string;
}
