import { useState, useEffect } from 'react';
import { Outlet, useNavigate } from 'react-router-dom';
import Sidebar from '../components/layout/Sidebar';
import Navbar from '../components/layout/Navbar';
import CameraScannerModal from '../components/CameraScannerModal';
import { useBarcodeScanner } from '../hooks/useBarcodeScanner';
import './MainLayout.css';

const MOBILE_BREAKPOINT = 1100;
const AUTO_COLLAPSE_BREAKPOINT = 1600;

function MainLayout() {
  const navigate = useNavigate();
  const [isSidebarCollapsed, setIsSidebarCollapsed] = useState(true);
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);
  const [isMobile, setIsMobile] = useState(window.innerWidth <= MOBILE_BREAKPOINT);
  const [isScannerModalOpen, setIsScannerModalOpen] = useState(false);

  // Detect mobile screen size
  useEffect(() => {
    const handleResize = () => {
      setIsMobile(window.innerWidth <= MOBILE_BREAKPOINT);

      // Keep sidebar collapsed for most screen sizes to maximize content space.
      if (window.innerWidth <= AUTO_COLLAPSE_BREAKPOINT) {
        setIsSidebarCollapsed(true);
      }

      // Close mobile menu when switching to desktop
      if (window.innerWidth > MOBILE_BREAKPOINT) {
        setIsMobileMenuOpen(false);
      }
    };

    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  const toggleSidebar = () => {
    if (isMobile) {
      // On mobile, toggle the overlay menu
      setIsMobileMenuOpen((prev) => !prev);
    } else {
      // On desktop, toggle collapse state
      setIsSidebarCollapsed((prev) => !prev);
    }
  };

  // Close mobile menu when clicking outside
  const handleOverlayClick = () => {
    if (isMobile && isMobileMenuOpen) {
      setIsMobileMenuOpen(false);
    }
  };

  // Enable barcode scanner globally in the admin area
  useBarcodeScanner({
    enabled: true,
    minLength: 5,
    maxLength: 50,
  });

  const normalizeScannedValue = (value: string): string => {
    const directValue = value.trim();
    if (!directValue) {
      return '';
    }

    // Supports QR values generated by EmployeeBarcode ("Employee ID: <id>").
    const employeeIdMatch = directValue.match(/employee\s*id\s*:\s*([^\n\r]+)/i);
    if (employeeIdMatch?.[1]) {
      return employeeIdMatch[1].trim();
    }

    return directValue;
  };

  const handleScanResult = (scannedValue: string) => {
    const employeeId = normalizeScannedValue(scannedValue);
    if (!employeeId) {
      return;
    }

    // Navigate to employee with ?scan=1&t=<timestamp> so re-scanning always triggers fresh navigation
    navigate(`/employees/${encodeURIComponent(employeeId)}?scan=1&t=${Date.now()}`);
  };

  return (
    <div className={`main-layout ${isSidebarCollapsed ? 'main-layout--sidebar-collapsed' : ''}`}>
      <Sidebar isCollapsed={isSidebarCollapsed} isMobileOpen={isMobileMenuOpen} />
      
      {/* Mobile overlay */}
      {isMobile && isMobileMenuOpen && (
        <div className="main-layout__overlay" onClick={handleOverlayClick} />
      )}
      
      <div className="main-layout__content">
        <Navbar
          onToggleSidebar={toggleSidebar}
          onOpenScanner={() => setIsScannerModalOpen(true)}
        />
        <main className="main-layout__main">
          <Outlet />
        </main>
      </div>

      <CameraScannerModal
        isOpen={isScannerModalOpen}
        onClose={() => setIsScannerModalOpen(false)}
        onDetected={handleScanResult}
      />
    </div>
  );
}

export default MainLayout;
